version: "3.9"

services:
  frontend:
    image: btn-frontend:latest
    container_name: btn-frontend
    build:
      context: .
      dockerfile: Dockerfile
    # environtment: .env.production
    # environment:
    #   - VITE_BACKEND_URL=http://localhost:3000 # URL backend
    # ports:
    #   - 8080:8080
    # command: bun run dev
    # command: sh -c "bun run build && bun run preview"
    volumes:
      # - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
    name: btn-frontend-node_modules

networks:
  default:
    name: internal
    external: true
